import { NextResponse } from "next/server"
import { sql, hasDb } from "@/lib/db"

const demoMenu = [
  {
    "id": 1,
    "category_id": KARBANADO,
    "name_uz": "Karbanado 25cm",
    "name_ru": "Карбанадо 25cm",
    "name_en": "Carbanado 25cm",
    "description_uz": "oq sous mazzarella pishlogi dudlangan go'sht tomat sousi qizil piyoz pormezon pishlog'i",
    "description_ru": "инуты пока сыр не растает. Подавать с рисом как гарнир.",
    "description_en": "descrip",
    "price": 25000,
    "image_url": "https://media.istockphoto.com/id/1735196496/photo/documenting-the-aftermath.webp?a=1&b=1&s=612x612&w=0&k=20&c=iE_lxcL8ZFQrZh-24shlkZb_szOHKRtMs4SMINoIFgw=",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 2,
    "category_id": 1,
    "name_uz": "Ovchi pitsa 25cm",
    "name_ru": "пицца охотник25cm",
    "name_en": "Hunter's pizza 25cm",
    "description_uz": "tomat sousi,mazzarella,ovchi kolbasalari,pomidor,tuzlangan bodiring,qizil piyoz,xantal sousi.",
    "description_ru": "Классическая итальянская пицца. Рецепт: 250г теста для пиццы (мука, вода, дрожжи и соль), 100г помидоров Сан Марцано, 100г сыра моцарелла, 5-6 листьев базилика, 1 столовая ложка оливкового масла, соль. Приготовление: Разогреть духовку до 250°C, измельчить помидоры для соуса, сформировать тесто диаметром 25-30 см, нанести соус и моцареллу, украсить базиликом и маслом, выпекать 6-8 минут.",
    "description_en": "Classic Italian pizza. Recipe: 250g pizza dough (flour, water, yeast, and salt), 100g San Marzano tomatoes, 100g mozzarella cheese, 5-6 basil leaves, 1 tablespoon olive oil, salt. Preparation: Preheat oven to 250°C, blend tomatoes into sauce, shape dough into 25-30 cm circle, add sauce and mozzarella, garnish with basil and oil, bake for 6-8 minutes.",
    "price": 35000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 3,
    "category_id": 1,
    "name_uz": "Joja va chorizo pishloqli 25cm",
    "name_ru":"сыр Джоджа и чоризо25cm",
    "name_en": "With chees and chorizo 25cm",
    "description_uz": "sous ranch,mazzarella,yoqimli chorizzo,mayin jo'ja,shirin bulg'orqalampiri,qizil piyoz,tomat,grilll sousi.",
    "description_ru": "Классическая итальянская пицца. Рецепт: 250г теста для пиццы (мука, вода, дрожжи и соль), 100г помидоров Сан Марцано, 100г сыра моцарелла, 5-6 листьев базилика, 1 столовая ложка оливкового масла, соль. Приготовление: Разогреть духовку до 250°C, измельчить помидоры для соуса, сформировать тесто диаметром 25-30 см, нанести соус и моцареллу, украсить базиликом и маслом, выпекать 6-8 минут.",
    "description_en": "Classic Italian pizza. Recipe: 250g pizza dough (flour, water, yeast, and salt), 100g San Marzano tomatoes, 100g mozzarella cheese, 5-6 basil leaves, 1 tablespoon olive oil, salt. Preparation: Preheat oven to 250°C, blend tomatoes into sauce, shape dough into 25-30 cm circle, add sauce and mozzarella, garnish with basil and oil, bake for 6-8 minutes.",
    "price": 35000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 4,
    "category_id": 1,
    "name_uz": "Tovuq va qoziqorin 25cm",
    "name_ru": "курица и грудка25cm",
    "name_en": "Chicken and mushroom 25cm",
    "description_uz": "sezar sousi,mazzarella,mayin tovuq,shampionyon qoziqorini,qizil piyoz,parmesan.",
    "description_ru": "Классическая итальянская пицца. Рецепт: 300г теста для пиццы (мука, вода, дрожжи и соль), 150г помидоров Сан Марцано, 150г сыра моцарелла, 6-8 листьев базилика, 2 столовые ложки оливкового масла, соль. Приготовление: Разогреть духовку до 250°C, измельчить помидоры для соуса, сформировать тесто диаметром 35 см, нанести соус и моцареллу, украсить базиликом и маслом, выпекать 8-10 минут.",
    "description_en": "Classic Italian pizza. Recipe: 300g pizza dough (flour, water, yeast, and salt), 150g San Marzano tomatoes, 150g mozzarella cheese, 6-8 basil leaves, 2 tablespoons olive oil, salt. Preparation: Preheat oven to 250°C, blend tomatoes into sauce, shape dough into 35 cm circle, add sauce and mozzarella, garnish with basil and oil, bake for 8-10 minutes.",
    "price": 35000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar ",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 5,
    "category_id": 1,
    "name_uz": "Ikki hissa peperoni 25cm",
    "name_ru": "два вклада пеперони25cm",
    "name_en": "Double peperoni 25cm",
    "description_uz": "pomidor sousi,mazzarella,pepperoni.",
    "description_ru": "Сырный и вкусный бургер. Рецепт: 200г фарш, 2 кусочка сыра чеддер, 1 помидор, 1 луковица, 1 булочка для бургера, кетчуп, соль и перец. Приготовление: Фарш посолить и поперчить, обжарить 5-7 минут, добавить сыр для плавления, поместить в булочку и украсить кетчупом.",
    "description_en": "Cheesy and delicious burger. Recipe: 200g ground meat, 2 cheddar cheese slices, 1 tomato, 1 onion, 1 burger bun, ketchup, salt and pepper. Preparation: Season meat with salt and pepper, fry for 5-7 minutes, add cheese to melt, place in bun, and garnish with ketchup.",
    "price": 28000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 6,
    "category_id": 1,
    "name_uz": "Sezar pitsa 25cm",
    "name_ru": "Цезарь пицца 25cm",
    "name_en": "Caesar pizza 25cm",
    "description_uz": " sezar sous,mayin tovuq go'shti,salat bargi,pomidor cherry,parmesan pishlog'i.",
    "description_ru": "Пицца с острой пепперони. Рецепт: 250г теста для пиццы, 100г томатного соуса, 100г моцареллы, 50г пепперони, 1 столовая ложка оливкового масла. Приготовление: Сформировать тесто 25-30 см, нанести соус и моцареллу, украсить пепперони, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with spicy pepperoni. Recipe: 250g pizza dough, 100g tomato sauce, 100g mozzarella, 50g pepperoni, 1 tablespoon olive oil. Preparation: Shape dough into 25-30 cm circle, add sauce and mozzarella, garnish with pepperoni, bake at 250°C for 6-8 minutes.",
    "price": 40000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 7,
    "category_id": 1,
    "name_uz": "Chizburger pitsa 25cm",
    "name_ru": "пицца с чизбургером 25",
    "name_en": "Cheeseburger pizza 25cm",
    "description_uz": "pishloq sousi,mazzarella,mol go'shti,tuzlangan bodiring,pomidor cherry,qizil piyoz.",
    "description_ru": "Пицца с четырьмя видами сыра. Рецепт: 300г теста, 150г томатного соуса, 50г моцареллы, 50г пармезана, 50г горгонзолы, 50г рикотты, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус и слоями сыр, запекать при 250°C 8-10 минут.",
    "description_en": "Pizza with four cheeses. Recipe: 300g dough, 150g tomato sauce, 50g mozzarella, 50g parmesan, 50g gorgonzola, 50g ricotta, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, layer sauce and cheeses, bake at 250°C for 8-10 minutes.",
    "price": 45000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar 35",
    "category_name_ru": "Пиццы 35",
    "category_name_en": "Pizzas 35"
  },
  {
    "id": 8,
    "category_id": 1,
    "name_uz": "Pishloqli joja 25cm ",
    "name_ru": "сырная Джоджа 25cm",
    "name_en": "Cheese pizza 25cm",
    "description_uz": "pishloq sousi,mazzarella pishlog'i,mayin tovuq,pomidor cherry.",
    "description_ru": "Бурер с куриным мясом. Рецепт: 200г куриного мяса, 1 помидор, 1 кусочек сыра, 1 булочка, майонез, соль и перец. Приготовление: Курицу посолить и поперчить, обжарить 5-7 минут, поместить в булочку и украсить майонезом.",
    "description_en": "Burger with chicken meat. Recipe: 200g chicken meat, 1 tomato, 1 cheese slice, 1 bun, mayonnaise, salt and pepper. Preparation: Season chicken with salt and pepper, fry for 5-7 minutes, place in bun, and garnish with mayonnaise.",
    "price": 30000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar ",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 9,
    "category_id": 1,
    "name_uz": "Meksika pitsa25cm",
    "name_ru": "мексиканская пицца25cm",
    "name_en": "Mexikan  pizza 25cm",
    "description_uz": "pomidor sousi,mazzarella pishlog'i,mol go'shti,chorizzo,pomidor,go'shtli mitbollar,shirin qalampir,barbekyu sousi.",
    "description_ru": "Пицца с ананасами и ветчиной. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г ветчины, 50г ананасов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу, ветчину и ананасы, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with pineapple and ham. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g ham, 50g pineapple, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, ham, and pineapple, bake at 250°C for 6-8 minutes.",
    "price": 42000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 10,
    "category_id": 1,
    "name_uz": "Gorgonzola nok25cm",
    "name_ru": "горгонзола груша 25cm",
    "name_en": "Gorgonzola pear25cm",
    "description_uz": "oq sous, mozzarella pishlog'i,nok,gorgonzola,asal,yong'oqlar.",
    "description_ru": "Вегетарианская пицца. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г красного лука, 50г болгарского перца, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и овощи, запекать при 250°C 8-10 минут.",
    "description_en": "Vegetarian pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g red onion, 50g bell pepper, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and vegetables, bake at 250°C for 8-10 minutes.",
    "price": 38000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar 35",
    "category_name_ru": "Пиццы 35",
    "category_name_en": "Pizzas 35"
  },
  {
    "id": 11,
    "category_id": 1,
    "name_uz": "Margaritta 25cm",
    "name_ru": "Маргарита 25cm",
    "name_en": "Margarita 25cm",
    "description_uz": "pomidor sousi,mazzarella pishlog'i,cherry pomidor,rayhon.",
    "description_ru": "Бургер с соусом BBQ. Рецепт: 200г мяса, 1 помидор, 1 кусочек сыра, 1 булочка, 2 столовые ложки соуса BBQ, соль и перец. Приготовление: Обжарить мясо с солью и перцем, смешать с соусом BBQ, поместить в булочку, добавить сыр и помидор.",
    "description_en": "BBQ sauce burger. Recipe: 200g meat, 1 tomato, 1 cheese slice, 1 bun, 2 tablespoons BBQ sauce, salt and pepper. Preparation: Fry meat with salt and pepper, mix with BBQ sauce, place in bun, add cheese and tomato.",
    "price": 32000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 12,
    "category_id": 1,
    "name_uz": "Goshtli 25cm",
    "name_ru": "мясной 25cm",
    "name_en": "Meaty 25cm",
    "description_uz": "pomidor sousi,mazzarella,mol go'shti,shirin qalampir,qizil piyoz.",
    "description_ru": "Пицца с грибами. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г грибов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу и грибы, запекать при 250°C 6-8 минут.",
    "description_en": "Mushroom pizza. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g mushrooms, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, and mushrooms, bake at 250°C for 6-8 minutes.",
    "price": 39000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 13,
    "category_id": 1,
    "name_uz": "Pepperoni goshtli 25cm",
    "name_ru": "пепперони мясной 25cm",
    "name_en": "Peperoni with meat 25cm",
    "description_uz": "pomidor sousi,mazzarella pishlog'i,pepperoni,go'shtli mitbollar.",
    "description_ru": "Пицца с морепродуктами. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г креветок, 50г мидий, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и морепродукты, запекать при 250°C 8-10 минут.",
    "description_en": "Seafood pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g shrimp, 50g mussels, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and seafood, bake at 250°C for 8-10 minutes.",
    "price": 48000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 14,
    "category_id": 1,
    "name_uz": "Peperoni 25cm",
    "name_ru": "пепперони 25cm",
    "name_en": "Peperoni 25cm",
    "description_uz": "pomidor sousi,mazzarella,pepperoni.",
    "description_ru": "Острый бургер с соусом. Рецепт: 200г мяса, 1 помидор, 1 кусочек сыра, 1 булочка, 2 столовые ложки острого соуса, соль и перец. Приготовление: Обжарить мясо с солью и перцем, смешать с острым соусом, поместить в булочку, добавить сыр.",
    "description_en": "Spicy burger with sauce. Recipe: 200g meat, 1 tomato, 1 cheese slice, 1 bun, 2 tablespoons spicy sauce, salt and pepper. Preparation: Fry meat with salt and pepper, mix with spicy sauce, place in bun, add cheese.",
    "price": 29000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 15,
    "category_id": 1,
    "name_uz": "Dengiz pitsa 25cm",
    "name_ru": "морская пицца 25cm",
    "name_en": "Sea pizza 25cm",
    "description_uz": "oq sous,lasos .",
    "description_ru": "Пицца с ветчиной и грибами. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г ветчины, 50г грибов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу, ветчину и грибы, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with ham and mushrooms. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g ham, 50g mushrooms, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, ham, and mushrooms, bake at 250°C for 6-8 minutes.",
    "price": 41000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 16,
    "category_id": 1,
    "name_uz": "Barbekyu pita 25cm",
    "name_ru": "барбекю 25cm",
    "name_en": "Barbeceu 25cm",
    "description_uz": "pomidor sousi mazzarella mayin tovuq pepperoni dudlangan gosh barbekyu sousi",
    "description_ru": "Пицца с разными видами мяса. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г мяса, 50г колбасы, 50г ветчины, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и мясо, запекать при 250°C 8-10 минут.",
    "description_en": "Pizza with various meats. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g meat, 50g sausage, 50g ham, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and meats, bake at 250°C for 8-10 minutes.",
    "price": 50000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 17,
    "category_id": 1,
    "name_uz": "Bekon va qoziqorin 25cm",
    "name_ru": "бекон и грудинка 25cm",
    "name_en": "bacon and mushroom25cm",
    "description_uz": "pomidor sousi mazzela pishlogi qoziqorin dudlangan gosht",
    "description_ru": "Вегетарианский бургер. Рецепт: 200г котлеты из фасоли, 1 помидор, 1 луковица, 1 булочка, майонез, соль и перец. Приготовление: Измельчить фасоль, сформировать котлету, обжарить 5-7 минут, поместить в булочку, добавить овощи и майонез.",
    "description_en": "Vegetarian burger. Recipe: 200g bean patty, 1 tomato, 1 onion, 1 bun, mayonnaise, salt and pepper. Preparation: Mash beans into a patty, fry for 5-7 minutes, place in bun, add vegetables and mayonnaise.",
    "price": 27000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 18,
    "category_id": 1,
    "name_uz": "Gavaya pitsa25cm",
    "name_ru": "Пицца Просciutto 25cm",
    "name_en": "Hawaiian pizza 25cm",
    "description_uz": "oq sous mazzela pishlogi mayin tovuq ananas",
    "description_ru": "Пицца с прошутто. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г прошутто, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу и прошутто, запекать при 250°C 6-8 минут.",
    "description_en": "Prosciutto pizza. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g prosciutto, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, and prosciutto, bake at 250°C for 6-8 minutes.",
    "price": 43000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 19,
    "category_id": 1,
    "name_uz": "5 Ta pishloqli pitsa 25cm",
    "name_ru": "5 сырных пицц 25cm",
    "name_en": "5 cheese pizza 25cm",
    "description_uz": "oq sous mazella pishlogi dudlangan pishloq cheddar gorgonzola dudlangan pishlogi",
    "description_ru": "Острая пицца. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г чили, 50г пепперони, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и острые ингредиенты, запекать при 250°C 8-10 минут.",
    "description_en": "Spicy pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g chili, 50g pepperoni, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and spicy ingredients, bake at 250°C for 8-10 minutes.",
    "price": 46000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 20,
    "category_id": 1,
    "name_uz": "Goshtli assorti 25cm",
    "name_ru": "Рыбный Бургер 25cm",
    "name_en": "Meat assortment 25cm",
    "description_uz": "pomidor sous mazzella pishlogi dudlangan gosh peperoni goshtli mitbollar asal hantal sousi ",
    "description_ru": "Бургер с рыбой. Рецепт: 200г рыбного филе, 1 помидор, 1 кусочек сыра, 1 булочка, тартар-соус, соль и перец. Приготовление: Обжарить рыбу с солью и перцем, поместить в булочку, добавить сыр и тартар-соус.",
    "description_en": "Fish burger. Recipe: 200g fish fillet, 1 tomato, 1 cheese slice, 1 bun, tartar sauce, salt and pepper. Preparation: Fry fish with salt and pepper, place in bun, add cheese and tartar sauce.",
    "price": 34000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 21,
    "category_id": 1,
    "name_uz": "Kilassik pitsa 25cm",
    "name_ru": "классическая пицца 25cm",
    "name_en": "Classic pizza 25cm",
    "description_uz": "pomidor sousi mazzela dudlangan mol  gosh pepperoni pomidor tuzlangan bodring",
    "description_ru": "Белая пицца без соуса. Рецепт: 250г теста, 100г рикотты, 100г моцареллы, 50г пармезана, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести слои сыра, запекать при 250°C 6-8 минут.",
    "description_en": "White pizza without sauce. Recipe: 250g dough, 100g ricotta, 100g mozzarella, 50g parmesan, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, layer cheeses, bake at 250°C for 6-8 minutes.",
    "price": 37000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
    {
    "id": 22,
    "category_id": 2,
    "name_uz": "Karbanado 30cm",
    "name_ru": "Милано Бургер",
    "name_en": "Carbanado 30cm",
    "description_uz": "Maxsus sous bilan tayyorlangan burger. Retsept: 200g qiyma go‘sht (bifshteks uchun), 1 ta pomidor (ingichka kesilgan), 1 ta pishloq bo‘lak (mozarella yoki cheddar), 1 ta burger bulochkasi, 2-3 yaproq marzori, maxsus sous (mayonez, zaytun yog‘i, sarimsoq va oregano aralashmasi), tuz va murch, 1 stakan guruch (garnir sifatida). Tayyorlash: Go‘shtni tuz va murch bilan zirva qilib, bifshteks shaklida ezib, 5-7 daqiqa qovuring. Bulochkani ikkiga bo‘lib qizdiring, sous surting, bifshteks, pomidor, pishloq va marzorni qo‘shing, yuqori qismni yoping, 1-2 daqiqa qizdirib, pishloq erishi uchun kutib oling. Garnir sifatida guruch bilan hamrohlash mumkin.",
    "description_ru": "Бургер с особым соусом. Рецепт: 200г фарш (для бифштекса), 1 помидор (тонко нарезанный), 1 кусочек сыра (моцарелла или чеддер), 1 булочка для бургера, 2-3 листа базилика, специальный соус (майонез, оливковое масло, чеснок и орегано), соль и перец, 1 стакан риса (как гарнир). Приготовление: Фарш посолить и поперчить, сформировать бифштекс, обжарить 5-7 минут. Булочку разрезать и слегка подогреть, намазать соусом, добавить бифштекс, помидор, сыр и базилик, накрыть верхней частью, подогреть 1-2 минуты, пока сыр не растает. Подавать с рисом как гарнир.",
    "description_en": "Burger with special sauce. Recipe: 200g ground meat (for patty), 1 tomato (thinly sliced), 1 cheese slice (mozzarella or cheddar), 1 burger bun, 2-3 basil leaves, special sauce (mayonnaise, olive oil, garlic, and oregano mix), salt and pepper, 1 cup rice (as garnish). Preparation: Season meat with salt and pepper, shape into a patty, and fry for 5-7 minutes. Slice and warm the bun, spread sauce, add patty, tomato, cheese, and basil, cover with top, heat for 1-2 minutes until cheese melts. Serve with rice as garnish.",
    "price": 25000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 23,
    "category_id": 2,
    "name_uz": "Joja va chorizo pishloqli30cm",
    "name_ru": "Маргарита",
    "name_en": "With chees and chorizo30cm",
    "description_uz": "Klassik italyan pitsasi. Retsept: 250g pizza xamiri (un, suv, xamirturush va tuzdan), 100g San Marzano pomidorlari, 100g mozzarella pishloqi, 5-6 yaproq bodom, 1 oshqoshi zaytun yog‘i, tuz. Tayyorlash: Pechka 250°C ga qizdirilsin, pomidorlarni maydalab sous tayyorlansin, xamirdan 25-30 sm diametrli shakl hosil qilinib, sous va mozzarella qo‘shilsin, bodom va yog‘ bilan bezatilsin, 6-8 daqiqa pishirilsin.",
    "description_ru": "Классическая итальянская пицца. Рецепт: 250г теста для пиццы (мука, вода, дрожжи и соль), 100г помидоров Сан Марцано, 100г сыра моцарелла, 5-6 листьев базилика, 1 столовая ложка оливкового масла, соль. Приготовление: Разогреть духовку до 250°C, измельчить помидоры для соуса, сформировать тесто диаметром 25-30 см, нанести соус и моцареллу, украсить базиликом и маслом, выпекать 6-8 минут.",
    "description_en": "Classic Italian pizza. Recipe: 250g pizza dough (flour, water, yeast, and salt), 100g San Marzano tomatoes, 100g mozzarella cheese, 5-6 basil leaves, 1 tablespoon olive oil, salt. Preparation: Preheat oven to 250°C, blend tomatoes into sauce, shape dough into 25-30 cm circle, add sauce and mozzarella, garnish with basil and oil, bake for 6-8 minutes.",
    "price": 35000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 24,
    "category_id": 2,
    "name_uz": "Tovuq va qoziqorin",
    "name_ru": "Pizza 35 cm",
    "name_en": "Chicken and mushroom",
    "description_uz": "Klassik italyan pitsasi. Retsept: 300g pizza xamiri (un, suv, xamirturush va tuzdan), 150g San Marzano pomidorlari, 150g mozzarella pishloqi, 6-8 yaproq bodom, 2 oshqoshi zaytun yog‘i, tuz. Tayyorlash: Pechka 250°C ga qizdirilsin, pomidorlarni maydalab sous tayyorlansin, xamirdan 35 sm diametrli shakl hosil qilinib, sous va mozzarella qo‘shilsin, bodom va yog‘ bilan bezatilsin, 8-10 daqiqa pishirilsin.",
    "description_ru": "Классическая итальянская пицца. Рецепт: 300г теста для пиццы (мука, вода, дрожжи и соль), 150г помидоров Сан Марцано, 150г сыра моцарелла, 6-8 листьев базилика, 2 столовые ложки оливкового масла, соль. Приготовление: Разогреть духовку до 250°C, измельчить помидоры для соуса, сформировать тесто диаметром 35 см, нанести соус и моцареллу, украсить базиликом и маслом, выпекать 8-10 минут.",
    "description_en": "Classic Italian pizza. Recipe: 300g pizza dough (flour, water, yeast, and salt), 150g San Marzano tomatoes, 150g mozzarella cheese, 6-8 basil leaves, 2 tablespoons olive oil, salt. Preparation: Preheat oven to 250°C, blend tomatoes into sauce, shape dough into 35 cm circle, add sauce and mozzarella, garnish with basil and oil, bake for 8-10 minutes.",
    "price": 35000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 25,
    "category_id": 2,
    "name_uz": "Ikki hissa peperoni30cm",
    "name_ru": "Сырный Бургер",
    "name_en": "Double peperoni30cm",
    "description_uz": "Pishloqli va mazali burger. Retsept: 200g qiyma go‘sht, 2 ta cheddar pishloq bo‘lagi, 1 ta pomidor, 1 ta piyoz, 1 ta burger bulochkasi, ketchup, tuz va murch. Tayyorlash: Go‘shtni tuz va murch bilan zirva qilib, 5-7 daqiqa qovuring, pishloqni qo‘shib eritsangiz, bulochka ichiga qo‘yib, ketchup bilan bezating.",
    "description_ru": "Сырный и вкусный бургер. Рецепт: 200г фарш, 2 кусочка сыра чеддер, 1 помидор, 1 луковица, 1 булочка для бургера, кетчуп, соль и перец. Приготовление: Фарш посолить и поперчить, обжарить 5-7 минут, добавить сыр для плавления, поместить в булочку и украсить кетчупом.",
    "description_en": "Cheesy and delicious burger. Recipe: 200g ground meat, 2 cheddar cheese slices, 1 tomato, 1 onion, 1 burger bun, ketchup, salt and pepper. Preparation: Season meat with salt and pepper, fry for 5-7 minutes, add cheese to melt, place in bun, and garnish with ketchup.",
    "price": 28000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id":26,
    "category_id": 2,
    "name_uz": "Sezar pitsa30cm",
    "name_ru": "Пицца Пепперони",
    "name_en": "Caesar pizza30cm",
    "description_uz": "Achchiq pepperoni bilan pitsa. Retsept: 250g pizza xamiri, 100g pomidor sousi, 100g mozzarella, 50g pepperoni, 1 oshqoshi zaytun yog‘i. Tayyorlash: Xamirdan 25-30 sm shakl yasab, sous va mozzarella qo‘shing, pepperoni bilan bezating, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с острой пепперони. Рецепт: 250г теста для пиццы, 100г томатного соуса, 100г моцареллы, 50г пепперони, 1 столовая ложка оливкового масла. Приготовление: Сформировать тесто 25-30 см, нанести соус и моцареллу, украсить пепперони, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with spicy pepperoni. Recipe: 250g pizza dough, 100g tomato sauce, 100g mozzarella, 50g pepperoni, 1 tablespoon olive oil. Preparation: Shape dough into 25-30 cm circle, add sauce and mozzarella, garnish with pepperoni, bake at 250°C for 6-8 minutes.",
    "price": 40000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 27,
    "category_id": 2,
    "name_uz": "Chizburger pitsa30cm",
    "name_ru": "Кватро Формаджи 35 см",
    "name_en": "Cheeseburger pizza30cm",
    "description_uz": "To‘rt xil pishloq bilan pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 50g mozzarella, 50g parmesan, 50g gorgonzola, 50g ricotta, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous va pishloqlarni qatlamlash, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Пицца с четырьмя видами сыра. Рецепт: 300г теста, 150г томатного соуса, 50г моцареллы, 50г пармезана, 50г горгонзолы, 50г рикотты, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус и слоями сыр, запекать при 250°C 8-10 минут.",
    "description_en": "Pizza with four cheeses. Recipe: 300g dough, 150g tomato sauce, 50g mozzarella, 50g parmesan, 50g gorgonzola, 50g ricotta, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, layer sauce and cheeses, bake at 250°C for 8-10 minutes.",
    "price": 45000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 28,
    "category_id": 2,
    "name_uz": "Pishloqli joja30 cm",
    "name_ru": "Куриный Бургер 30 cm",
    "name_en": "Cheese pizza 30 cm",
    "description_uz": "Tovuq go‘shti bilan burger. Retsept: 200g tovuq go‘shti, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, mayonez, tuz va murch. Tayyorlash: Tovuqni tuz va murch bilan zirva qilib, 5-7 daqiqa qovuring, bulochka ichiga qo‘yib, mayonez bilan bezating.",
    "description_ru": "Бургер с куриным мясом. Рецепт: 200г куриного мяса, 1 помидор, 1 кусочек сыра, 1 булочка, майонез, соль и перец. Приготовление: Курицу посолить и поперчить, обжарить 5-7 минут, поместить в булочку и украсить майонезом.",
    "description_en": "Burger with chicken meat. Recipe: 200g chicken meat, 1 tomato, 1 cheese slice, 1 bun, mayonnaise, salt and pepper. Preparation: Season chicken with salt and pepper, fry for 5-7 minutes, place in bun, and garnish with mayonnaise.",
    "price": 30000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar30 cm",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers30 cm"
  },
  {
    "id": 29,
    "category_id": 2,
    "name_uz": "Meksika pitsa30cm",
    "name_ru": "Гавайская Пицца",
    "name_en": "Mexikan pizza30cm",
    "description_uz": "Ananas va jambon bilan pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g jambon, 50g ananas, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella, jambon va ananas qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с ананасами и ветчиной. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г ветчины, 50г ананасов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу, ветчину и ананасы, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with pineapple and ham. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g ham, 50g pineapple, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, ham, and pineapple, bake at 250°C for 6-8 minutes.",
    "price": 42000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar30cm",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 30,
    "category_id": 2,
    "name_uz": "Gorgonzola nok30cm",
    "name_ru": "Вегетарианская 35 см",
    "name_en": "Gorgonzola pear30cm",
    "description_uz": "Vegetarian pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g qizil piyoz, 50g ko‘k lalanga, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va sabzavotlarni qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Вегетарианская пицца. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г красного лука, 50г болгарского перца, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и овощи, запекать при 250°C 8-10 минут.",
    "description_en": "Vegetarian pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g red onion, 50g bell pepper, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and vegetables, bake at 250°C for 8-10 minutes.",
    "price": 38000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 31,
    "category_id": 2,
    "name_uz": "Margaritta30cm",
    "name_ru": "Бургер с BBQ",
    "name_en": "Margarita",
    "description_uz": "BBQ sousli burger. Retsept: 200g go‘sht, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, 2 oshqoshi BBQ sous, tuz va murch. Tayyorlash: Go‘shtni tuz va murch bilan qovuring, BBQ sous bilan aralashtirib, bulochka ichiga qo‘yib, pishloq va pomidor qo‘shing.",
    "description_ru": "Бургер с соусом BBQ. Рецепт: 200г мяса, 1 помидор, 1 кусочек сыра, 1 булочка, 2 столовые ложки соуса BBQ, соль и перец. Приготовление: Обжарить мясо с солью и перцем, смешать с соусом BBQ, поместить в булочку, добавить сыр и помидор.",
    "description_en": "BBQ sauce burger. Recipe: 200g meat, 1 tomato, 1 cheese slice, 1 bun, 2 tablespoons BBQ sauce, salt and pepper. Preparation: Fry meat with salt and pepper, mix with BBQ sauce, place in bun, add cheese and tomato.",
    "price": 32000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 32,
    "category_id": 2,
    "name_uz": "Goshtli 30cm",
    "name_ru": "Пицца с Грибами",
    "name_en": "Goshtlin 30cm",
    "description_uz": "Qo‘ziqorinli pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g qo‘ziqorin, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella va qo‘ziqorin qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с грибами. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г грибов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу и грибы, запекать при 250°C 6-8 минут.",
    "description_en": "Mushroom pizza. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g mushrooms, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, and mushrooms, bake at 250°C for 6-8 minutes.",
    "price": 39000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 33,
    "category_id": 2,
    "name_uz": "Pepperoni goshtli 30cm",
    "name_ru": "Морская 35 см",
    "name_en": "Peperoni with meat30cm",
    "description_uz": "Dengiz mahsulotlari bilan pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g kreveka, 50g midiya, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va dengiz mahsulotlarini qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Пицца с морепродуктами. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г креветок, 50г мидий, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и морепродукты, запекать при 250°C 8-10 минут.",
    "description_en": "Seafood pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g shrimp, 50g mussels, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and seafood, bake at 250°C for 8-10 minutes.",
    "price": 48000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 34,
    "category_id": 2,
    "name_uz": "Peperoni30cm",
    "name_ru": "Острый Бургер",
    "name_en": "Peperoni30cm",
    "description_uz": "Achchiq sousli burger. Retsept: 200g go‘sht, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, 2 oshqoshi achchiq sous, tuz va murch. Tayyorlash: Go‘shtni tuz va murch bilan qovuring, achchiq sous bilan aralashtirib, bulochka ichiga qo‘yib, pishloq qo‘shing.",
    "description_ru": "Острый бургер с соусом. Рецепт: 200г мяса, 1 помидор, 1 кусочек сыра, 1 булочка, 2 столовые ложки острого соуса, соль и перец. Приготовление: Обжарить мясо с солью и перцем, смешать с острым соусом, поместить в булочку, добавить сыр.",
    "description_en": "Spicy burger with sauce. Recipe: 200g meat, 1 tomato, 1 cheese slice, 1 bun, 2 tablespoons spicy sauce, salt and pepper. Preparation: Fry meat with salt and pepper, mix with spicy sauce, place in bun, add cheese.",
    "price": 29000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 35,
    "category_id": 2,
    "name_uz": "Dengiz pitsa30cm",
    "name_ru": "Пицца Каприччоза",
    "name_en": "Seafood pizza30cm",
    "description_uz": "Jambon va qo‘ziqorinli pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g jambon, 50g qo‘ziqorin, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella, jambon va qo‘ziqorin qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с ветчиной и грибами. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г ветчины, 50г грибов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу, ветчину и грибы, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with ham and mushrooms. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g ham, 50g mushrooms, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, ham, and mushrooms, bake at 250°C for 6-8 minutes.",
    "price": 41000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 36,
    "category_id": 2,
    "name_uz": "Barbekyu pita30cm",
    "name_ru": "Мясная 35 см",
    "name_en": "Barbeceu30 cm",
    "description_uz": "Turli go‘shtli pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g go‘sht, 50g kolbasa, 50g jambon, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va go‘shtlarni qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Пицца с разными видами мяса. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г мяса, 50г колбасы, 50г ветчины, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и мясо, запекать при 250°C 8-10 минут.",
    "description_en": "Pizza with various meats. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g meat, 50g sausage, 50g ham, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and meats, bake at 250°C for 8-10 minutes.",
    "price": 50000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 37,
    "category_id": 2,
    "name_uz": "Bekon va qoziqorin30cm",
    "name_ru": "Вегетарианский Бургер",
    "name_en": "Bacon and mushroom30cm",
    "description_uz": "Sabzavotli burger. Retsept: 200g loviya kotletasi, 1 ta pomidor, 1 ta piyoz, 1 ta bulochka, mayonez, tuz va murch. Tayyorlash: Loviyani maydalab kotleta yasab, 5-7 daqiqa qovuring, bulochka ichiga qo‘yib, sabzavotlar va mayonez qo‘shing.",
    "description_ru": "Вегетарианский бургер. Рецепт: 200г котлеты из фасоли, 1 помидор, 1 луковица, 1 булочка, майонез, соль и перец. Приготовление: Измельчить фасоль, сформировать котлету, обжарить 5-7 минут, поместить в булочку, добавить овощи и майонез.",
    "description_en": "Vegetarian burger. Recipe: 200g bean patty, 1 tomato, 1 onion, 1 bun, mayonnaise, salt and pepper. Preparation: Mash beans into a patty, fry for 5-7 minutes, place in bun, add vegetables and mayonnaise.",
    "price": 27000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 38,
    "category_id": 2,
    "name_uz": "Gavaya pitsa30cm",
    "name_ru": "Пицца Просciutto",
    "name_en": "Hawaiian pizza30cm",
    "description_uz": "Prosciutto bilan pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g prosciutto, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella va prosciutto qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с прошутто. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г прошутто, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу и прошутто, запекать при 250°C 6-8 минут.",
    "description_en": "Prosciutto pizza. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g prosciutto, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, and prosciutto, bake at 250°C for 6-8 minutes.",
    "price": 43000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 39,
    "category_id": 2,
    "name_uz": "5 Ta pishloqli pitsa30cm",
    "name_ru": "Острая 35 см",
    "name_en": "5 cheese pizza30cm",
    "description_uz": "Achchiq pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g chili, 50g pepperoni, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va achchiq ingredientlarni qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Острая пицца. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г чили, 50г пепперони, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и острые ингредиенты, запекать при 250°C 8-10 минут.",
    "description_en": "Spicy pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g chili, 50g pepperoni, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and spicy ingredients, bake at 250°C for 8-10 minutes.",
    "price": 46000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 40,
    "category_id": 2,
    "name_uz": "Goshtli assorti30cm",
    "name_ru": "Рыбный Бургер",
    "name_en": "Meat assortment30cm",
    "description_uz": "Baliq bilan burger. Retsept: 200g baliq file, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, tartar sous, tuz va murch. Tayyorlash: Baliqni tuz va murch bilan qovuring, bulochka ichiga qo‘yib, pishloq va tartar sous qo‘shing.",
    "description_ru": "Бургер с рыбой. Рецепт: 200г рыбного филе, 1 помидор, 1 кусочек сыра, 1 булочка, тартар-соус, соль и перец. Приготовление: Обжарить рыбу с солью и перцем, поместить в булочку, добавить сыр и тартар-соус.",
    "description_en": "Fish burger. Recipe: 200g fish fillet, 1 tomato, 1 cheese slice, 1 bun, tartar sauce, salt and pepper. Preparation: Fry fish with salt and pepper, place in bun, add cheese and tartar sauce.",
    "price": 34000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 41,
    "category_id": 2,
    "name_uz": "Kilassik pitsa30cm",
    "name_ru": "Белая Пицца",
    "name_en": "Classic pizza30cm",
    "description_uz": "Soussiz oq pitsa. Retsept: 250g xamiri, 100g ricotta, 100g mozzarella, 50g parmesan, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, pishloqlarni qatlamlash, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Белая пицца без соуса. Рецепт: 250г теста, 100г рикотты, 100г моцареллы, 50г пармезана, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести слои сыра, запекать при 250°C 6-8 минут.",
    "description_en": "White pizza without sauce. Recipe: 250g dough, 100g ricotta, 100g mozzarella, 50g parmesan, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, layer cheeses, bake at 250°C for 6-8 minutes.",
    "price": 37000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
    {
    "id": 42,
    "category_id": 3,
    "name_uz": "Karbanado35cm",
    "name_ru": "Милано Бургер",
    "name_en": "Carbanado35cm",
    "description_uz": "Maxsus sous bilan tayyorlangan burger. Retsept: 200g qiyma go‘sht (bifshteks uchun), 1 ta pomidor (ingichka kesilgan), 1 ta pishloq bo‘lak (mozarella yoki cheddar), 1 ta burger bulochkasi, 2-3 yaproq marzori, maxsus sous (mayonez, zaytun yog‘i, sarimsoq va oregano aralashmasi), tuz va murch, 1 stakan guruch (garnir sifatida). Tayyorlash: Go‘shtni tuz va murch bilan zirva qilib, bifshteks shaklida ezib, 5-7 daqiqa qovuring. Bulochkani ikkiga bo‘lib qizdiring, sous surting, bifshteks, pomidor, pishloq va marzorni qo‘shing, yuqori qismni yoping, 1-2 daqiqa qizdirib, pishloq erishi uchun kutib oling. Garnir sifatida guruch bilan hamrohlash mumkin.",
    "description_ru": "Бургер с особым соусом. Рецепт: 200г фарш (для бифштекса), 1 помидор (тонко нарезанный), 1 кусочек сыра (моцарелла или чеддер), 1 булочка для бургера, 2-3 листа базилика, специальный соус (майонез, оливковое масло, чеснок и орегано), соль и перец, 1 стакан риса (как гарнир). Приготовление: Фарш посолить и поперчить, сформировать бифштекс, обжарить 5-7 минут. Булочку разрезать и слегка подогреть, намазать соусом, добавить бифштекс, помидор, сыр и базилик, накрыть верхней частью, подогреть 1-2 минуты, пока сыр не растает. Подавать с рисом как гарнир.",
    "description_en": "Burger with special sauce. Recipe: 200g ground meat (for patty), 1 tomato (thinly sliced), 1 cheese slice (mozzarella or cheddar), 1 burger bun, 2-3 basil leaves, special sauce (mayonnaise, olive oil, garlic, and oregano mix), salt and pepper, 1 cup rice (as garnish). Preparation: Season meat with salt and pepper, shape into a patty, and fry for 5-7 minutes. Slice and warm the bun, spread sauce, add patty, tomato, cheese, and basil, cover with top, heat for 1-2 minutes until cheese melts. Serve with rice as garnish.",
    "price": 25000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 43,
    "category_id": 3,
    "name_uz": "Ovchi pitsa35cm",
    "name_ru": "Маргарита",
    "name_en": "Hunter's pizza35cm",
    "description_uz": "Klassik italyan pitsasi. Retsept: 250g pizza xamiri (un, suv, xamirturush va tuzdan), 100g San Marzano pomidorlari, 100g mozzarella pishloqi, 5-6 yaproq bodom, 1 oshqoshi zaytun yog‘i, tuz. Tayyorlash: Pechka 250°C ga qizdirilsin, pomidorlarni maydalab sous tayyorlansin, xamirdan 25-30 sm diametrli shakl hosil qilinib, sous va mozzarella qo‘shilsin, bodom va yog‘ bilan bezatilsin, 6-8 daqiqa pishirilsin.",
    "description_ru": "Классическая итальянская пицца. Рецепт: 250г теста для пиццы (мука, вода, дрожжи и соль), 100г помидоров Сан Марцано, 100г сыра моцарелла, 5-6 листьев базилика, 1 столовая ложка оливкового масла, соль. Приготовление: Разогреть духовку до 250°C, измельчить помидоры для соуса, сформировать тесто диаметром 25-30 см, нанести соус и моцареллу, украсить базиликом и маслом, выпекать 6-8 минут.",
    "description_en": "Classic Italian pizza. Recipe: 250g pizza dough (flour, water, yeast, and salt), 100g San Marzano tomatoes, 100g mozzarella cheese, 5-6 basil leaves, 1 tablespoon olive oil, salt. Preparation: Preheat oven to 250°C, blend tomatoes into sauce, shape dough into 25-30 cm circle, add sauce and mozzarella, garnish with basil and oil, bake for 6-8 minutes.",
    "price": 35000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 44,
    "category_id": 3,
    "name_uz": "Tovuq va qoziqorin35cm",
    "name_ru": "Pizza 35 cm",
    "name_en": "Chicken and mushroom35cm",
    "description_uz": "Klassik italyan pitsasi. Retsept: 300g pizza xamiri (un, suv, xamirturush va tuzdan), 150g San Marzano pomidorlari, 150g mozzarella pishloqi, 6-8 yaproq bodom, 2 oshqoshi zaytun yog‘i, tuz. Tayyorlash: Pechka 250°C ga qizdirilsin, pomidorlarni maydalab sous tayyorlansin, xamirdan 35 sm diametrli shakl hosil qilinib, sous va mozzarella qo‘shilsin, bodom va yog‘ bilan bezatilsin, 8-10 daqiqa pishirilsin.",
    "description_ru": "Классическая итальянская пицца. Рецепт: 300г теста для пиццы (мука, вода, дрожжи и соль), 150г помидоров Сан Марцано, 150г сыра моцарелла, 6-8 листьев базилика, 2 столовые ложки оливкового масла, соль. Приготовление: Разогреть духовку до 250°C, измельчить помидоры для соуса, сформировать тесто диаметром 35 см, нанести соус и моцареллу, украсить базиликом и маслом, выпекать 8-10 минут.",
    "description_en": "Classic Italian pizza. Recipe: 300g pizza dough (flour, water, yeast, and salt), 150g San Marzano tomatoes, 150g mozzarella cheese, 6-8 basil leaves, 2 tablespoons olive oil, salt. Preparation: Preheat oven to 250°C, blend tomatoes into sauce, shape dough into 35 cm circle, add sauce and mozzarella, garnish with basil and oil, bake for 8-10 minutes.",
    "price": 35000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 45,
    "category_id": 3,
    "name_uz": "Ikki hissa peperoni35cm",
    "name_ru": "Сырный Бургер",
    "name_en": "Double peperoni35cm",
    "description_uz": "Pishloqli va mazali burger. Retsept: 200g qiyma go‘sht, 2 ta cheddar pishloq bo‘lagi, 1 ta pomidor, 1 ta piyoz, 1 ta burger bulochkasi, ketchup, tuz va murch. Tayyorlash: Go‘shtni tuz va murch bilan zirva qilib, 5-7 daqiqa qovuring, pishloqni qo‘shib eritsangiz, bulochka ichiga qo‘yib, ketchup bilan bezating.",
    "description_ru": "Сырный и вкусный бургер. Рецепт: 200г фарш, 2 кусочка сыра чеддер, 1 помидор, 1 луковица, 1 булочка для бургера, кетчуп, соль и перец. Приготовление: Фарш посолить и поперчить, обжарить 5-7 минут, добавить сыр для плавления, поместить в булочку и украсить кетчупом.",
    "description_en": "Cheesy and delicious burger. Recipe: 200g ground meat, 2 cheddar cheese slices, 1 tomato, 1 onion, 1 burger bun, ketchup, salt and pepper. Preparation: Season meat with salt and pepper, fry for 5-7 minutes, add cheese to melt, place in bun, and garnish with ketchup.",
    "price": 28000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 46,
    "category_id": 3,
    "name_uz": "Sezar pitsa35cm",
    "name_ru": "Пицца Пепперони",
    "name_en": "Caesar pizza35cm",
    "description_uz": "Achchiq pepperoni bilan pitsa. Retsept: 250g pizza xamiri, 100g pomidor sousi, 100g mozzarella, 50g pepperoni, 1 oshqoshi zaytun yog‘i. Tayyorlash: Xamirdan 25-30 sm shakl yasab, sous va mozzarella qo‘shing, pepperoni bilan bezating, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с острой пепперони. Рецепт: 250г теста для пиццы, 100г томатного соуса, 100г моцареллы, 50г пепперони, 1 столовая ложка оливкового масла. Приготовление: Сформировать тесто 25-30 см, нанести соус и моцареллу, украсить пепперони, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with spicy pepperoni. Recipe: 250g pizza dough, 100g tomato sauce, 100g mozzarella, 50g pepperoni, 1 tablespoon olive oil. Preparation: Shape dough into 25-30 cm circle, add sauce and mozzarella, garnish with pepperoni, bake at 250°C for 6-8 minutes.",
    "price": 40000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 47,
    "category_id": 3,
    "name_uz": "Chizburger pitsa 35cm",
    "name_ru": "Кватро Формаджи 35 см",
    "name_en": "Cheeseburger pizza 35cm",
    "description_uz": "To‘rt xil pishloq bilan pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 50g mozzarella, 50g parmesan, 50g gorgonzola, 50g ricotta, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous va pishloqlarni qatlamlash, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Пицца с четырьмя видами сыра. Рецепт: 300г теста, 150г томатного соуса, 50г моцареллы, 50г пармезана, 50г горгонзолы, 50г рикотты, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус и слоями сыр, запекать при 250°C 8-10 минут.",
    "description_en": "Pizza with four cheeses. Recipe: 300g dough, 150g tomato sauce, 50g mozzarella, 50g parmesan, 50g gorgonzola, 50g ricotta, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, layer sauce and cheeses, bake at 250°C for 8-10 minutes.",
    "price": 45000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 48,
    "category_id": 3,
    "name_uz": "Pishloqli joja35cm",
    "name_ru": "Куриный Бургер",
    "name_en": "Cheese pizza35cm",
    "description_uz": "Tovuq go‘shti bilan burger. Retsept: 200g tovuq go‘shti, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, mayonez, tuz va murch. Tayyorlash: Tovuqni tuz va murch bilan zirva qilib, 5-7 daqiqa qovuring, bulochka ichiga qo‘yib, mayonez bilan bezating.",
    "description_ru": "Бургер с куриным мясом. Рецепт: 200г куриного мяса, 1 помидор, 1 кусочек сыра, 1 булочка, майонез, соль и перец. Приготовление: Курицу посолить и поперчить, обжарить 5-7 минут, поместить в булочку и украсить майонезом.",
    "description_en": "Burger with chicken meat. Recipe: 200g chicken meat, 1 tomato, 1 cheese slice, 1 bun, mayonnaise, salt and pepper. Preparation: Season chicken with salt and pepper, fry for 5-7 minutes, place in bun, and garnish with mayonnaise.",
    "price": 30000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 49,
    "category_id": 3,
    "name_uz": "Meksika pitsa35cm",
    "name_ru": "Гавайская Пицца",
    "name_en": "Mexikan pizza35cm",
    "description_uz": "Ananas va jambon bilan pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g jambon, 50g ananas, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella, jambon va ananas qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с ананасами и ветчиной. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г ветчины, 50г ананасов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу, ветчину и ананасы, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with pineapple and ham. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g ham, 50g pineapple, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, ham, and pineapple, bake at 250°C for 6-8 minutes.",
    "price": 42000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 50,
    "category_id": 3,
    "name_uz": "Gorgonzola nok35cm",
    "name_ru": "Вегетарианская 35 см",
    "name_en": "Gorgonzola pear35 cm ",
    "description_uz": "Vegetarian pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g qizil piyoz, 50g ko‘k lalanga, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va sabzavotlarni qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Вегетарианская пицца. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г красного лука, 50г болгарского перца, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и овощи, запекать при 250°C 8-10 минут.",
    "description_en": "Vegetarian pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g red onion, 50g bell pepper, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and vegetables, bake at 250°C for 8-10 minutes.",
    "price": 38000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 51,
    "category_id": 3,
    "name_uz": "Margaritta35cm",
    "name_ru": "Бургер с BBQ",
    "name_en": "Margarita35 cm ",
    "description_uz": "BBQ sousli burger. Retsept: 200g go‘sht, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, 2 oshqoshi BBQ sous, tuz va murch. Tayyorlash: Go‘shtni tuz va murch bilan qovuring, BBQ sous bilan aralashtirib, bulochka ichiga qo‘yib, pishloq va pomidor qo‘shing.",
    "description_ru": "Бургер с соусом BBQ. Рецепт: 200г мяса, 1 помидор, 1 кусочек сыра, 1 булочка, 2 столовые ложки соуса BBQ, соль и перец. Приготовление: Обжарить мясо с солью и перцем, смешать с соусом BBQ, поместить в булочку, добавить сыр и помидор.",
    "description_en": "BBQ sauce burger. Recipe: 200g meat, 1 tomato, 1 cheese slice, 1 bun, 2 tablespoons BBQ sauce, salt and pepper. Preparation: Fry meat with salt and pepper, mix with BBQ sauce, place in bun, add cheese and tomato.",
    "price": 32000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 52,
    "category_id": 3,
    "name_uz": "Goshtli 35cm ",
    "name_ru": "Пицца с Грибами",
    "name_en": "Goshtlin 35cm ",
    "description_uz": "Qo‘ziqorinli pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g qo‘ziqorin, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella va qo‘ziqorin qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с грибами. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г грибов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу и грибы, запекать при 250°C 6-8 минут.",
    "description_en": "Mushroom pizza. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g mushrooms, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, and mushrooms, bake at 250°C for 6-8 minutes.",
    "price": 39000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 53,
    "category_id": 3,
    "name_uz": "Pepperoni goshtli 35cm ",
    "name_ru": "Морская 35 см",
    "name_en": "Peperoni with meat 35cm ",
    "description_uz": "Dengiz mahsulotlari bilan pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g kreveka, 50g midiya, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va dengiz mahsulotlarini qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Пицца с морепродуктами. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г креветок, 50г мидий, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и морепродукты, запекать при 250°C 8-10 минут.",
    "description_en": "Seafood pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g shrimp, 50g mussels, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and seafood, bake at 250°C for 8-10 minutes.",
    "price": 48000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 54,
    "category_id": 3,
    "name_uz": "Peperoni35cm",
    "name_ru": "Острый Бургер",
    "name_en": "Peperoni35cm ",
    "description_uz": "Achchiq sousli burger. Retsept: 200g go‘sht, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, 2 oshqoshi achchiq sous, tuz va murch. Tayyorlash: Go‘shtni tuz va murch bilan qovuring, achchiq sous bilan aralashtirib, bulochka ichiga qo‘yib, pishloq qo‘shing.",
    "description_ru": "Острый бургер с соусом. Рецепт: 200г мяса, 1 помидор, 1 кусочек сыра, 1 булочка, 2 столовые ложки острого соуса, соль и перец. Приготовление: Обжарить мясо с солью и перцем, смешать с острым соусом, поместить в булочку, добавить сыр.",
    "description_en": "Spicy burger with sauce. Recipe: 200g meat, 1 tomato, 1 cheese slice, 1 bun, 2 tablespoons spicy sauce, salt and pepper. Preparation: Fry meat with salt and pepper, mix with spicy sauce, place in bun, add cheese.",
    "price": 29000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 55,
    "category_id": 3,
    "name_uz": "Dengiz pitsa35cm",
    "name_ru": "Пицца Каприччоза",
    "name_en": "Seafood pizza",
    "description_uz": "Jambon va qo‘ziqorinli pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g jambon, 50g qo‘ziqorin, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella, jambon va qo‘ziqorin qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с ветчиной и грибами. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г ветчины, 50г грибов, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу, ветчину и грибы, запекать при 250°C 6-8 минут.",
    "description_en": "Pizza with ham and mushrooms. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g ham, 50g mushrooms, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, ham, and mushrooms, bake at 250°C for 6-8 minutes.",
    "price": 41000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 56,
    "category_id": 3,
    "name_uz": "Barbekyu pita35cm",
    "name_ru": "Мясная 35 см",
    "name_en": "Barbeceu35cm",
    "description_uz": "Turli go‘shtli pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g go‘sht, 50g kolbasa, 50g jambon, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va go‘shtlarni qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Пицца с разными видами мяса. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г мяса, 50г колбасы, 50г ветчины, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и мясо, запекать при 250°C 8-10 минут.",
    "description_en": "Pizza with various meats. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g meat, 50g sausage, 50g ham, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and meats, bake at 250°C for 8-10 minutes.",
    "price": 50000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 57,
    "category_id": 3,
    "name_uz": "Bekon va qoziqorin35cm",
    "name_ru": "Вегетарианский Бургер",
    "name_en": "Bacon and mushroom35 cm",
    "description_uz": "Sabzavotli burger. Retsept: 200g loviya kotletasi, 1 ta pomidor, 1 ta piyoz, 1 ta bulochka, mayonez, tuz va murch. Tayyorlash: Loviyani maydalab kotleta yasab, 5-7 daqiqa qovuring, bulochka ichiga qo‘yib, sabzavotlar va mayonez qo‘shing.",
    "description_ru": "Вегетарианский бургер. Рецепт: 200г котлеты из фасоли, 1 помидор, 1 луковица, 1 булочка, майонез, соль и перец. Приготовление: Измельчить фасоль, сформировать котлету, обжарить 5-7 минут, поместить в булочку, добавить овощи и майонез.",
    "description_en": "Vegetarian burger. Recipe: 200g bean patty, 1 tomato, 1 onion, 1 bun, mayonnaise, salt and pepper. Preparation: Mash beans into a patty, fry for 5-7 minutes, place in bun, add vegetables and mayonnaise.",
    "price": 27000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 58,
    "category_id": 3,
    "name_uz": "Gavaya pitsa35cm",
    "name_ru": "Пицца Просciutto",
    "name_en": "Hawaiian pizza35cm",
    "description_uz": "Prosciutto bilan pitsa. Retsept: 250g xamiri, 100g pomidor sousi, 100g mozzarella, 50g prosciutto, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, sous, mozzarella va prosciutto qo‘shing, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Пицца с прошутто. Рецепт: 250г теста, 100г томатного соуса, 100г моцареллы, 50г прошутто, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести соус, моцареллу и прошутто, запекать при 250°C 6-8 минут.",
    "description_en": "Prosciutto pizza. Recipe: 250g dough, 100g tomato sauce, 100g mozzarella, 50g prosciutto, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, add sauce, mozzarella, and prosciutto, bake at 250°C for 6-8 minutes.",
    "price": 43000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 59,
    "category_id": 3,
    "name_uz": "5 Ta pishloqli pitsa35cm",
    "name_ru": "Острая 35 см",
    "name_en": "5 cheese pizza35cm",
    "description_uz": "Achchiq pitsa. Retsept: 300g xamiri, 150g pomidor sousi, 100g mozzarella, 50g chili, 50g pepperoni, 2 oshqoshi zaytun yog‘i. Tayyorlash: 35 sm shakl yasab, sous, mozzarella va achchiq ingredientlarni qo‘shing, 250°C da 8-10 daqiqa pishiring.",
    "description_ru": "Острая пицца. Рецепт: 300г теста, 150г томатного соуса, 100г моцареллы, 50г чили, 50г пепперони, 2 столовые ложки оливкового масла. Приготовление: Сформировать 35 см круг, нанести соус, моцареллу и острые ингредиенты, запекать при 250°C 8-10 минут.",
    "description_en": "Spicy pizza. Recipe: 300g dough, 150g tomato sauce, 100g mozzarella, 50g chili, 50g pepperoni, 2 tablespoons olive oil. Preparation: Shape into 35 cm circle, add sauce, mozzarella, and spicy ingredients, bake at 250°C for 8-10 minutes.",
    "price": 46000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar35",
    "category_name_ru": "Пиццы35",
    "category_name_en": "Pizzas35"
  },
  {
    "id": 60,
    "category_id": 3,
    "name_uz": "Goshtli assorti 35cm",
    "name_ru": "мясной ассортимент 35cm",
    "name_en": "Meat assortment35cm",
    "description_uz": "Baliq bilan burger. Retsept: 200g baliq file, 1 ta pomidor, 1 ta pishloq, 1 ta bulochka, tartar sous, tuz va murch. Tayyorlash: Baliqni tuz va murch bilan qovuring, bulochka ichiga qo‘yib, pishloq va tartar sous qo‘shing.",
    "description_ru": "Бургер с рыбой. Рецепт: 200г рыбного филе, 1 помидор, 1 кусочек сыра, 1 булочка, тартар-соус, соль и перец. Приготовление: Обжарить рыбу с солью и перцем, поместить в булочку, добавить сыр и тартар-соус.",
    "description_en": "Fish burger. Recipe: 200g fish fillet, 1 tomato, 1 cheese slice, 1 bun, tartar sauce, salt and pepper. Preparation: Fry fish with salt and pepper, place in bun, add cheese and tartar sauce.",
    "price": 34000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Burgerlar",
    "category_name_ru": "Бургеры",
    "category_name_en": "Burgers"
  },
  {
    "id": 61,
    "category_id": 3,
    "name_uz": "Klassik pitsa 35cm",
    "name_ru": "классическая пицца 35cm",
    "name_en": "Classic pizza35cm",
    "description_uz": "Soussiz oq pitsa. Retsept: 250g xamiri, 100g ricotta, 100g mozzarella, 50g parmesan, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, pishloqlarni qatlamlash, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Белая пицца без соуса. Рецепт: 250г теста, 100г рикотты, 100г моцареллы, 50г пармезана, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести слои сыра, запекать при 250°C 6-8 минут.",
    "description_en": "White pizza without sauce. Recipe: 250g dough, 100g ricotta, 100g mozzarella, 50g parmesan, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, layer cheeses, bake at 250°C for 6-8 minutes.",
    "price": 37000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 62,
    "category_id": 3,
    "name_uz": "Joja va chorizo pishloqli 35cm",
    "name_ru": "с курицей и сыром чоризо 35cm",
    "name_en": "with cheese and chorizo 35cm",
    "description_uz": "Soussiz oq pitsa. Retsept: 250g xamiri, 100g ricotta, 100g mozzarella, 50g parmesan, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, pishloqlarni qatlamlash, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Белая пицца без соуса. Рецепт: 250г теста, 100г рикотты, 100г моцареллы, 50г пармезана, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести слои сыра, запекать при 250°C 6-8 минут.",
    "description_en": "White pizza without sauce. Recipe: 250g dough, 100g ricotta, 100g mozzarella, 50g parmesan, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, layer cheeses, bake at 250°C for 6-8 minutes.",
    "price": 37000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
  {
    "id": 63,
    "category_id": 2,
    "name_uz": "Ovchi pitsa 30cm",
    "name_ru": "пицца охотник 30cm",
    "name_en": "hunter's pizza 30cm",
    "description_uz": "Soussiz oq pitsa. Retsept: 250g xamiri, 100g ricotta, 100g mozzarella, 50g parmesan, 1 oshqoshi zaytun yog‘i. Tayyorlash: 25-30 sm shakl yasab, pishloqlarni qatlamlash, 250°C da 6-8 daqiqa pishiring.",
    "description_ru": "Белая пицца без соуса. Рецепт: 250г теста, 100г рикотты, 100г моцареллы, 50г пармезана, 1 столовая ложка оливкового масла. Приготовление: Сформировать 25-30 см круг, нанести слои сыра, запекать при 250°C 6-8 минут.",
    "description_en": "White pizza without sauce. Recipe: 250g dough, 100g ricotta, 100g mozzarella, 50g parmesan, 1 tablespoon olive oil. Preparation: Shape into 25-30 cm circle, layer cheeses, bake at 250°C for 6-8 minutes.",
    "price": 37000,
    "image_url": "/placeholder.svg?height=300&width=300",
    "category_name_uz": "Pitsalar",
    "category_name_ru": "Пиццы",
    "category_name_en": "Pizzas"
  },
]

/**
 * GET /api/menu – returns all available menu items.
 * Falls back to hard-coded demo data if the database is unreachable.
 */
export async function GET() {
  if (!hasDb) {
    return NextResponse.json({ menuItems: demoMenu })
  }

  try {
    const rows = await sql`
      SELECT
        mi.*,
        c.name_uz AS category_name_uz,
        c.name_ru AS category_name_ru,
        c.name_en AS category_name_en
      FROM menu_items mi
      LEFT JOIN categories c ON mi.category_id = c.id
      WHERE mi.is_available = true
      ORDER BY c.id, mi.name_uz
    `
    return NextResponse.json({ menuItems: rows })
  } catch (err) {
    console.error("DB error in /api/menu:", (err as Error).message)
    return NextResponse.json({ menuItems: demoMenu })
  }
}
